## 4. 넘파이

shift + enter : 셀 실행 <br>
alt + enter : 셀 추가

4.1 다차원 배열 객체 ndarray

In [ ]:
# 백만개의 정수를 저장하는 넘파이 배열과 파이썬 리스트를 생성한다
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [ ]:
# %timeit으로 실행 속도 측정
# 넘파이를 사용한 코드가 훨씬 빠르다
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

In [ ]:
# 1차원 배열 생성하기
arr1 = np.array([6, 7.5, 8, 0, 1])
arr1

In [ ]:
# 2차원 배열 생성하기
import numpy as np
arr2 = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
arr2

In [ ]:
# 자료형, 차원, 행열크기 확인하기
print(arr1.dtype, arr1.ndim, arr1.shape)
print(arr2.dtype, arr2.ndim, arr2.shape)

In [ ]:
# 10개 크기의 1차원 배열 생성. 모든 값이 0.0으로 초기화
np.zeros(10)
# 3행 6열 크기의 2차원 배열 생성. 모든 값이 0.0으로 초기화
np.zeros((3, 6))
# 2,3,2 크기의 3차원 배열 생성. 임의의 값이 들어감
np.empty((2, 3, 2))

In [ ]:
# 파이썬의 range 함수와 같은 기능
np.arange(15)

In [ ]:
# 배열의 타입을 직접 지정
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)

In [ ]:
# astype : 배열의 형변환
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64) # int -> float64
print(float_arr, float_arr.dtype)

In [ ]:
# 형변환
# float -> int
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr, arr.dtype)
int_arr = arr.astype(np.int32)
print(int_arr, int_arr.dtype)

In [ ]:
# 형변환
# string -> float
# float 까지만 쓰면 넘파이가 자동으로 float64로 설정함
numeric_strings = np.array(["1.25", "-9.6", "42"])
str_arr = numeric_strings.astype(float)
print(str_arr, str_arr.dtype)

In [ ]:
# 넘파이 배열의 산술 연산
# for문을 쓰지 않아도 각 원소에 계산이 적용됨
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr + arr)
print(arr - arr)

In [ ]:
# 비교연산을 하면 불리언 배열이 반환됨
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr

In [ ]:
# 넘파일 배열 생성
arr = np.arange(10)
print(arr)

# 배열 슬라이스
print(arr[5:8])

# 배열 슬라이스에 숫자를 넣으면 값이 전파되어, 
# arr[5] arr[6] arr[7]에 모두 12가 저장됨
arr[5:8] = 12
print(arr)
print(arr[5:8])

In [ ]:
# 슬라이스 배열을 변수에 담기
arr_slice = arr[5:8]
print(arr_slice)
# 슬라이스 배열의 값을 바꾸면 원본 배열도 함꼐 변경됨
# 파이썬의 리스트 슬라이스는 '복사본'을 만들지만,
# 넘파이 배열의 슬라이스는 '뷰(view)'로 원본 데이터를 그대로 보여줌
arr_slice[1] = 12345
print(arr)

In [ ]:
# [:]은 배열의 모든값
arr_slice[:] = 64
arr

In [ ]:
# 2차원 배열 생성 
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 2차원 배열에서 각 요소는 1차원 배열
arr2d[2]

In [ ]:
# 3행 3열 배열에서 특정 요소 꺼내기
print(arr2d[0][2])
print(arr2d[0, 2])

In [ ]:
# 2차원 배열 슬라이스하기
# 열을 기준으로 슬라이스 (0번부터 1번까지)
print(arr2d[:2])

# 각 열에서 슬라이스 하기
# 배열[행범위, 앞에서 선택한 행에서 열범위]
# 앞의 두 행(0,1)에서 열 1부터 끝까지(1,2) 선택
print(arr2d[:2, 1:])

In [ ]:
# 1행에서 열 0~1까지 선택
lower_dim_slice = arr2d[1, :2]
print(lower_dim_slice)
# 1차원 2개 크기 배열
print(lower_dim_slice.shape)

In [ ]:
# 앞의 두 행(0,1)에서 세 번째 열만 선택 (1치원)
print(arr2d[:2, 2])

# 모든 행에서 첫 번째 열만 선택 (2차원)
print(arr2d[:, :1])

In [ ]:
# 불리언 색인
# 학생 목록
students = np.array(["철수", "영희", "민수", "철수", "영희"])
# 학생별 대출 이력
books = np.array([
    ["수학의 정석", 7],   # 책제목, 대출일수
    ["해리포터", 14],
    ["파이썬 입문", 10],
    ["한국사", 5],
    ["데미안", 12]
])
# 학생목록과 대출이력은 인덱스 위치 기준으로 대응

In [ ]:
# 넘파이 배열에 비교연산을 쓰면 불리언 배열 반환
print(students == "철수")

# 불리언 배열 [True False False True False]를 books 배열에 적용하면,
# True인 위치(0번째, 3번째)의 행만 뽑혀 나옴
books[students == "철수"]

In [ ]:
# 철수의 대출 기록 보기
# 1: => 두번째 열부터 마지막까지 (대출일수)
print(books[students == "철수", 1:])
# 1 => 두번째 열만 (대출일수)
print(books[students == "철수", 1])

# 철수가 아닌 항목 찾기
print(students != "철수")

In [ ]:
# 불리언색인을 사용해서 값 수정하기
# "수학의 정석"을 찾아서 책제목 바꾸기
books[books == "수학의 정석"] = "자바의 정석"
print(books)

# 철수가 아닌 행 전체를 7로 바꾸기
books[students != "철수"] = 7
print(books)

4.1.6 팬시색인

In [ ]:
# 데이터 준비
# 8행 4열 크기의 배열 생성
# zeros : 모든 요소를 0으로 초기화
arr = np.zeros((8, 4))
# 0부터 7까지 반복하면서
# 각 행을 숫자로 채우기
for i in range(8):
    arr[i] = i
arr

In [ ]:
# 배열에서 4행, 3행, 0행, 6행 순서대로 골라오기 
# 팬시 인덱스 : 인덱스를 리스트로 넣으면 원하는 행만 나옴
arr[[4, 3, 0, 6]]

In [ ]:
# 0부터 31까지 숫자들을 만들고 8행 4열 크기의 배열로 만들기
arr = np.arange(32).reshape((8, 4))
print(arr)
# 행과 열을 지정해서 원하는 요소 뽑기
# (1행, 0열), (5행, 3열), (7행, 1열), (2행, 2열)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
# 이중 팬시 인덱스
# 먼저 배열에서 1,5,7,2 행을 골라옴 -> 부분배열에서 열을  0,3,1,2 순서로 다시 재배열
# print(arr[[1, 5, 7, 2]]) # 중간 과정
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
# (1행,0열), (5행,3열), (7행,1열), (2행,2열) 요소를 선택
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]]) # 이전 값 확인

# 이전에 선택한 요소들의 값을 모두 0으로 변경
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

4.1.7 배열 전치와 축 바꾸기

In [22]:
# 배열의 행과 열 바꾸기

# 0부터 14까지 숫자 목록 생성
# reshape((3, 5)) : 3행 5열 짜리 2차원 배열 생성
arr = np.arange(15).reshape((3, 5))
print(arr)

# .T : 행과 열 바꾸기
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [23]:
# 5행 3열 크기의 2차원 배열 생성
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)

# .dot : 배열의 열에대한 유사도를 구하는 공식 (유사도를 구하는 이유는 뒤에서!)
np.dot(arr.T, arr)

# np.dot()과 동일
arr.T @ arr

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]


array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [25]:
# 데이터 확인
print(arr) 
# 행(0축)과 열(1축)을 서로 바꾸기 (전과 동일)
arr.swapaxes(0, 1)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]


array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

4.2 난수 생성

In [ ]:
# 4행 4열 배열 생성
samples = np.random.standard_normal(size=(4, 4))
samples

In [ ]:
# 파이썬 내장 random 모듈과 넘파이의 random 모듈의 성능 비교
from random import normalvariate
N = 1_000_000 # 백만개

# 리스트 컴프리헨션으로 난수를 하나씩 생성하기 때문에 속도가 느림
# normalvariate(0, 1) : 평균 0, 표준편차 1인 난수 하나 생성 (-3~+3)
%timeit samples = [normalvariate(0, 1) for _ in range(N)] # 수초 걸림

# 넘파이는 백만개의 난수를 한번에 생성하기 때문에 속도가 훨씬 빠름
%timeit np.random.standard_normal(N) # 몇십 ms 걸림

In [ ]:
# 난수 생성기 만들기
# seed에 같은 숫자를 넣으면 -> 항상 같은 난수가 생성됨
rng = np.random.default_rng(seed=12345)
print(type(rng))

# 2x3 배열 생성
data1 = rng.standard_normal((2, 3))
print(data1, type(data1))

In [ ]:
rng2 = np.random.default_rng(seed=12345)
data2 = rng2.standard_normal((2, 3))
data2

4.3 유니버설 함수

In [ ]:
# 0~9 배열 생성
arr = np.arange(10)

# 유니버설 함수 : 배열의 각 원소를 빠르게 처리하는 함수
# 유니버설 함수를 사용하면 한번에 계산할 수 있음

# add : 모든 배열 요소에 n만큼 더하기
print('원본:', arr)
np.add(arr, 1)

In [ ]:
# 평균0 표준편차1의 정규분포 (-3~+3)
# 난수 8개 생성
x = rng.standard_normal(8)
y = rng.standard_normal(8)
print(x)
print(y)

# maximum : 두 배열을 비교해서 최대값 구하기
np.maximum(x, y)

In [ ]:
# 파이선 기본 함수 사용
import math

# sqrt : 제곱근 계산
# print(math.sqrt(9))
# print(math.sqrt(16))

# exp : 지수 함수 계산 (e^x)
print(math.exp(1))
print(math.exp(2))
print(math.exp(5))

In [ ]:
# 넘파이 배열 함수 사용
# sqrt : 제곱근
print(np.sqrt(arr))
# exp : 지수
print(np.exp(arr))

4.4 배열을 이용한 프로그래밍

In [ ]:
# for문 없이 간단히 배열 연산 가능

# np.arange(3) : 0~2 배열 생성
# meshgrid : 좌표격자를 만들기 위해 2개의 2차원 배열을 반환
# xs : x축 기준 격자
# ys : y축 기준 격자
xs, ys = np.meshgrid(np.arange(3), np.arange(3))
print(xs)
print(ys)

# 두 배열 더하기
z = xs + ys
z

In [ ]:
# -5 이상 5 미만 까지 0.01 간격으로 값 생성
# -5부터 4.99까지 0.01씩 증가하는 값의 배열
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
print(xs)
print(ys)
# 이렇게 만든 2차원 배열은 맷플롯립을 이용해 시각화할 수 있음

In [ ]:
# 배열로 조건문 만들기
# 두개의 데이터 배열
arr1 = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
arr2 = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
# 조건 배열 (불리언 배열)
cond = np.array([True, False, True, True, False])

In [ ]:
# coda가 true면 arr1, false면 arr2를 선택
result = [(x if c else y)
          for x, y, c in zip(arr1, arr2, cond)]
result

In [ ]:
# 이번에는 넘파이로 조건문 쓰기
# 파이썬 기본 코드보다 더 빠르고, 다차원배열에도 적용 가능
result = np.where(cond, xarr, yarr)
result

In [ ]:
# 평균0 표준편차1인 난수 생성
# 4x4 크기의 배열 생성
arr = rng.standard_normal((4, 4))
print(arr)

# 불리언 배열 대신 조건식을 넣을 수 있음
# where(조건, 참일때값, 거짓일때값)
# 요소가 0보다 크면 2, 아니면 -2로 치환
np.where(arr > 0, 2, -2)

In [ ]:
# 수학/통계 메소드

# 평균0 표준편차1인 난수 생성
# 5x4 크기의 배열 생성
arr = rng.standard_normal((5, 4))
print(arr)

# 배열 객체 메소드로 평균 구하기
arr.mean()
# 넘파이 메소드로 평균 구하기 (배열 외에도 리스트, 튜플 등 사용 가능)
np.mean(arr)
# 배열의 합계 구하기
arr.sum()

In [ ]:
# 모든 행의 합계 구하기
# axis=0 => 행 방향으로 계산
print(arr.sum(axis=0))

# 모든 열의 평균 구하기
# axis=1 => 열 방향으로 계산
print(arr.mean(axis=1))

In [ ]:
# cumsum : 누적값 구하기
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()
# 0
# 0+1 = 1
# 0+1+2 = 3
# ...

In [ ]:
# 3행 3열 크기의 배열 생성
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr)
# 열 방향으로 누적값 구하기 (위->아래)
print(arr.cumsum(axis=0))
# 행 방향으로 누적값 구하기 (왼->오)
print(arr.cumsum(axis=1))

In [ ]:
# 불리언 배열을 위한 메소드

# 평균0 표준편차1인 정규분포에서 난수 100개 생성
arr = rng.standard_normal(100)

# 양수 개수
# arr > 0 => 배열의 요소를 하나씩 비교해서, 맞으면 1 아니면 0이 반환됨
result1 = (arr > 0).sum()
print(result1)

# 음수 개수
result2 = (arr <= 0).sum()
print(result2)

In [ ]:
# 불리언 배열 생성
bools = np.array([False, False, True, False])
# any : 하나이상의 true가 있는지 검사
print(bools.any())
# all : 모든 요소가 true인지 검사
print(bools.all())

In [ ]:
# 정렬
# 평균0 표준편차1인 정규분포에서 난수 6개 생성
arr = rng.standard_normal(6)
print(arr)
# 배열 정렬
arr.sort()
print(arr)

In [ ]:
# 평균0 표준편차1인 정규분포에서 
# 5행 3열 크기의 난수 2차원 배열 생성
arr = rng.standard_normal((5, 3))
arr

In [ ]:
# 열 기준으로 정렬
arr.sort(axis=0)
print(arr)

# 행 기준으로 정렬
arr.sort(axis=1)
print(arr)

In [ ]:
# 배열이 아닌 넘파이의 sort함수를 사용
# 원본배열은 그대로 두고, 정렬된 새로운 배열을 반환함
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)

print('원본 배열:', arr2)
print('새로운 배열:', sorted_arr2)

4.5 배열 데이터의 파일 입출력

In [27]:
# 0부터 9까지 담긴 숫자 배열 생성
arr = np.arange(10)

# 배열을 파일로 저장 (넘파일 전용 파일 .npy)
# 파일은 폴더 경로에서 확인
np.save("some_array", arr)

In [28]:
# 파일 불러오기
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# 새로운 배열 생성
arr2 = np.arange(10, 20)
# 배열 여러개를 한번에 저장
# 키=배열로 묶어서 저장
np.savez("array_archive.npz", a=arr, b=arr2)

In [33]:
# 파일 불러오기
arch = np.load("array_archive.npz")
# b 배열만 꺼내기
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])